# Generated by Django 5.0.4 on 2024-05-27 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_alter_post_user_alter_postcomment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmedia',
            name='user',
        ),
        migrations.AddField(
            model_name='postmedia',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='Post.post'),
            preserve_default=False,
        ),
    ]
