# Generated by Django 5.0.4 on 2024-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_remove_postmedia_user_postmedia_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default=2, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PostMedia',
        ),
    ]
